language: node_js

node_js: "10"

cache: npm

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_ID
    secret_access_key: $AWS_ACCESS_KEY
    region: us-east-2
    app: Launch Dashboard
    env: LaunchDashboard-env
    bucket_name: elasticbeanstalk-us-east-2-583257580903
    bucket_path: Code
    on:
      branch: master
